# Generated by Django 5.1.3 on 2024-12-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('we_are_by', models.IntegerField()),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
